name: Publish
on:
  release:
    types: [ created ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      # リリースタグを取得して package.json を更新
      - name: Update package.json version
        run: |
          RELEASE_VERSION=${{ github.event.release.tag_name }}
          VERSION=${RELEASE_VERSION#v}
          jq ".version = \"${VERSION}\"" ./package.json > package.tmp.json
          mv package.tmp.json ./package.json
          jq ".version = \"${VERSION}\"" ./package-lock.json > package.tmp.json
          mv package.tmp.json ./package-lock.json

      - name: NPM install
        run: npm install

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch > /dev/null
          
          # リリースタグがどのブランチに紐づいているかを取得
          BRANCH_NAME=$(git branch -r --contains "$(git rev-parse "${{ github.event.release.tag_name }}")" | grep -v 'HEAD' | head -n 1 | sed 's|^[ \t]*||;s|[ \t]*$||' | sed 's|^origin/||')
          if [ -z "$BRANCH_NAME" ]; then
            echo "Error: The release tag ${{ github.event.release.tag_name }} does not belong to any branch."
            exit 1
          fi
          
          # リリースユーザー情報を設定
          RELEASE_AUTHOR_NAME="${{ github.event.release.author.login }}"
          RELEASE_AUTHOR_EMAIL="${{ github.event.release.author.email || github.event.release.author.login }}@users.noreply.github.com"

          git config --global user.name "$RELEASE_AUTHOR_NAME"
          git config --global user.email "$RELEASE_AUTHOR_EMAIL"

          # 変更をコミットしてプッシュ
          git add .
          git commit -m "Release ${{ github.event.release.tag_name }}"
          git push origin HEAD:$BRANCH_NAME
          
          # リリースタグを強制的に再生成
          git tag -f ${{ github.event.release.tag_name }}
          git push origin --tags --force